#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
#Role.create(:role1=>"Obama", :role2=>"Batman")
#Role.create(:role1=>"Jesus", :role2=>"Richard Dawkins")
f = File.open("roles.txt")
c = f.read

c.each_line do |line|
  arr = line.split(", ")
  puts "Role1 #{arr[0]}, Role2 #{arr[1]}" 
  Role.create(:role1=>arr[0], :role2=>arr[1].split("\n")[0])  
  
end
